# Input data
mvals: "data/mvals_brain.csv.gz"
pheno: "data/pheno_brain.csv"

# EWAS model
association_variable: "ethnicity"
stratified_ewas: "no"
stratify_variables: ["cancer_type"]

# DMR (optional)
dmr_analysis: "no"
genome_build: "hg38"

# Performance
chunk_size: 1000
processing_type: "multicore"
workers: 2

# Output
out_directory: "results/"
out_type: ".csv.gz"
out_prefix: "brain"

# Annotation files
annotation_manifest: "annotation_files/HM450.hg38.manifest.gencode.v36.tsv.gz"
snp_annotation: "annotation_files/HM450.hg38.snp.tsv.gz"
