# Input data
mvals: "data/mvals.csv.gz"
pheno: "data/pheno.csv"

# EWAS model
association_variable: "ethnicity"
stratified_ewas: "yes"
stratify_variables: ["cancer_type"]

# DMR (optional)
dmr_analysis: "no"
genome_build: "hg38"

# Performance
chunk_size: 1000
processing_type: "multicore"
workers: 2

# Output
out_directory: "results/"
out_type: ".csv.gz"
