# Input data
mvals: "data/kidney_mvals.csv"
pheno: "data/kidney_phenotype.csv"

# EWAS model parameters
association_variable: "Type"  # Primary solid Tumor vs. Solid Tissue Normal
stratified_ewas: "no"         

# Annotation files
annotation_manifest: "data/manifest_450k.csv"
snp_annotation: "data/snp_450k.csv"

# Parallelization
chunk_size: 5000
processing_type: "multicore"
workers: 4

# Output
out_directory: "results_kidney/"
out_type: ".csv.gz"
out_prefix: "kidney"
