# Input data
mvals: "data/mvals.csv.gz"        # Your methylation matrix (M-values)
pheno: "data/pheno.csv"           # Your phenotype/metadata file

# EWAS model
association_variable: "cancer_type"   # The variable you want to test
stratified_ewas: "no"
stratify_variables: []

# DMR (optional)
dmr_analysis: "no"
genome_build: "hg38"

# Performance
chunk_size: 1000
processing_type: "multicore"
workers: 2

# Output
out_directory: "results/"
out_type: ".csv.gz"
