# Input data
mvals: "data/kidney_mvals.csv"
pheno: "data/kidney_phenotype.csv"
association_variable: "Type"

# EWAS model parameters
association_variable: "Type"  # Primary solid Tumor vs. Solid Tissue Normal
stratified_ewas: "no"    
stratify_variables: []

# Annotation files
annotation_manifest: "annotation_files/HM450.hg38.manifest.gencode.v36.tsv.gz"
snp_annotation: "annotation_files/HM450.hg38.snp.tsv.gz"

# DMR Analysis
dmr_analysis: "no"
genome_build: "hg38"

# Parallelization
chunk_size: 5000
processing_type: "multicore"
workers: 4

# Output
out_directory: "results_kidney/"
out_type: ".csv.gz"
out_prefix: "kidney"
